/quad_0/body_pose:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile
/quad_0/lidar_pose:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile
/quad_0/cloud:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile
/grid_map/occupancy:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile
/grid_map/occupancy_inflate:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile
